# This is my numpy notebook

In [1]:
import numpy as np

1D array

In [2]:
num = np.array([10,20,30,40,50])
print(num)

[10 20 30 40 50]


In [3]:
type(num)

numpy.ndarray

In [4]:
num.dtype

dtype('int32')

In [5]:
newArray = np.array([1,2,3,4,5],dtype="float")
newArray

array([1., 2., 3., 4., 5.])

In [6]:
newArray[0]

1.0

In [7]:
newArray[1]

2.0

In [8]:
newArray[-1]

5.0

Check the dimension of an array

In [9]:
num.ndim

1

In [10]:
num.shape

(5,)

In [11]:
num.size

5

In [12]:
num2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
num2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
num2.ndim

2

In [15]:
num2.dtype

dtype('int32')

In [16]:
num2.shape

(3, 3)

In [17]:
num2.size

9

In [18]:
num3 = np.array([[10,20,30],[40,50,60]])

In [19]:
num3

array([[10, 20, 30],
       [40, 50, 60]])

In [20]:
num3.shape

(2, 3)

In [21]:
num3.min()

10

In [22]:
num3.max()

60

In [23]:
num3.mean()

35.0

In [24]:
num3.sum()

210

In [25]:
num3.sum(axis=0)

array([50, 70, 90])

In [26]:
num3.sum(axis=1)

array([ 60, 150])

In [27]:
numA = np.arange(5)
numA

array([0, 1, 2, 3, 4])

In [28]:
numB = np.array([10,20,30,40,50])
numB

array([10, 20, 30, 40, 50])

In [29]:
numA+numB

array([10, 21, 32, 43, 54])

In [30]:
numA-numB

array([-10, -19, -28, -37, -46])

In [31]:
numA/numB

array([0.        , 0.05      , 0.06666667, 0.075     , 0.08      ])

In [32]:
numA*numB

array([  0,  20,  60, 120, 200])

In [33]:
num3.reshape(3,2)

array([[10, 20],
       [30, 40],
       [50, 60]])

In [34]:
num3.ravel()

array([10, 20, 30, 40, 50, 60])